### PR TITLE
Chart is now hidden by default

### PR DESCRIPTION
**Pull request by eldang**
I feel silly making such a tiny pull request, but this was all it took.  I guess I can pat myself on the back for designing it that way last year....

### CODE REVIEW

**Review by coregis — CHANGES_REQUESTED** [review]
This works really well! What do you think about centering the 'Show History Chart' text/arrows? It looks ok as it is, but I think it might be a little more obvious (especially for first time visitors) if it were centered in the map div. I think we should keep the 'Hide Chart' text and X on the right.

**Comment by eldang** [comment]
> What do you think about centering the 'Show History Chart' text/arrows?

How's this?

**Review by coregis — APPROVED** [review]
¡Muy bueno!

**Comment by coregis** [comment]
Looks great, much more intuitive! Thank you

**Pull request merged**
