### PR TITLE
Add charter company zoom control

### PR DESCRIPTION
**Pull request by eldang**
This should be ready to merge now.

Progress:
- [x] Load the charters layers without making it visible
- [x] Add second set of zoom controls, which is populated from the charters layer
- [x] Filter displayed points
- [x] Adapt the chart code to be able to be controlled from the charters controls as well as the districts one
- [x] Decide what to make the chart do when the viewer zooms to a charter
- [x] Implement that in the chart code
- [ ] Improve the text prompts for the zoom controls (may need RYHT's input on the wording)

### CODE REVIEW

**Comment by eldang** [comment]
The functionality for this is basically in place now, but I'm using charter campus ID numbers in place of names in a few places to get things working.  I'll straighten that out when the data are ready, and then switch this from a draft to a real PR.

**Comment by eldang** [comment]
@coregis I think this is now ready, but it adds enough complexity that it's definitely worth you doing some QA on first.  Things I'm particularly wary of:

1. Until yesterday I had some bugs in the interaction between the two autocompleting text boxes.  I think I have that straightened out, but it's definitely worth testing them both and moving from one to the other.
2. What do you think of the wording of the prompts in the sidebar?  They are of course easy to change if you can think of clearer ways to describe them.
3. I think the interaction of changing the chart when you click on a point is now confusing.  I'm not sure whether to redesign that or remove it, and would like your feedback.

**Comment by coregis** [comment]
Overall this is looking good! Some specific responses to your points:

1. Yes, there is still some weirdness going on. For example, if I type in an ISD in the top auto-complete window, it works as expected. For example, if I choose Houston ISD, the map zooms to the Houston ISD. However, if I then use the charter company filter to select KIPP Public Charter Schools, the map zooms to the extent of the filtered points for KIPP, again, the expected behavior. However, both Houston ISD and KIPP Public Charter Schools persist in their respective auto-complete boxes, so if I then choose 'Texas School Districts' in the ISD drop-down to zoom to the full state extent...nothing happens. I have to choose a different district, then choose 'Texas School Districts' to zoom to full state extent. Same deal for charter companies.

2. I think the wording is helpful, but we might consider making a couple of changes to the charter school description, for example changing 'filter' to 'see', and the last sentence to something like 'Choose the top entry to see all Charter Campuses'.

3. I agree. I think we need to check in with RYHT about which behavior they want to see on map click;  my opinion is that a popup should display only the details for the selected campus, and the charts update only when an ISD or charter company is selected via auto-complete or drop-down. Too confusing if a user selects charter company, then clicks on map to see the name of a charter campus, and the chart switches to stats for the ISD. 

A couple of other thoughts/observations:  

-I don't know how complicated this is, but it would be helpful if the text in the autocomplete window disappeared when the user chooses the top entry in either dropdown (either Texas School Districts or All charter schools)

-The charter school point filter is working really well, but I noticed that it only filters for the _selected year_, and if the map is animated or stepped forward/backward, all schools re-appear. I understand it might be challenging to maintain the filter across time, but it might be confusing if schools appear that are not within the selected company. Also, the filtering does not appear to work if the animation is ongoing when the charter company is selected.

-We had previously discussed limiting the ISD drop-down list to just those districts that contain charter schools; is that something we still want to do? If so here are the details for the relevant Mapbox layer:
URL:  core-gis.36t9c225
Layer:  texas_ISDs_with_charter_campu-1g69fh

-Do you want me to merge this PR? Or are you going to keep trucking? Either is fine with me, just let me know

**Comment by eldang** [comment]
@coregis Whether to merge now or not is basically a client-management decision.  I will get back to this this afternoon, but if you see any value in showing the current state to RYHT then go ahead and merge it - just let them know that we're still working on the rough edges.

Same goes for changing the ISD list.  It's no trouble technically, but I don't recall RYHT ever deciding if they want us to do that or not.  There may be less reason to now that it's not necessary to hunt through the whole dropdown to find a particular one, so I think it's worth asking them again.

I think your response to point 1 is actually closely related to the issue of clearing the text box contents, so I'm going to try and address those two things together.  And I'd completely missed that advancing the year clears the charter filter, but I am facepalming over that.  Both things function by setting a filter on the same dataset, so I need to add some more state tracking so that the changes are additive, rather than one replacing the other.

**Comment by eldang** [comment]
I'll make fresh commits as I fix things, but I'll take care not to commit anything that seems incomplete, so you should be safe merging this at any point if you decide to do so.

**Comment by eldang** [comment]
@coregis I think I've now dealt with the key issues.  New behaviours:

1. Filters are now additive, and clearing the charters filter leaves the year filter set.
2. Selecting a district by typing its name gets that option selected in the corresponding dropdown, _and gets the other dropdown cleared_ so the two dropdowns between them reflect the current state.
3. The text boxes get cleared after use so they never have old values lying around in them.

**Comment by coregis** [comment]
@eldang NICE WORK! This is ready to share with RYHT, and we can ask them to give us direction wrt on-click behavior for charts. I think it will be super helpful for them to have this new-and-improved version to respond to.

**Pull request merged**
