### PR TITLE
Synchronises popups to the selected year

### PR DESCRIPTION
**Pull request by eldang**

### CODE REVIEW

**Comment by eldang** [comment]
ACTUALLY: hold off on looking at this one, I just realised a tidier way to do it.

**Comment by eldang** [comment]
OK, now it's ready.  One issue to watch out for: sometimes I think a campus changing name from one year to the next is causing the popup to get hidden.

**Comment by eldang** [comment]
Aaaaaand now that's fixed.  I had forgotten that RYHT were giving us a persistent campus ID, but now I'm using that.

**Review by coregis — APPROVED** [review]
These changes look good, although I'm somewhat concerned that the changes I made to the popup code in the load-new-data branch might run afoul of your work here. Perhaps we can sort it out on Friday 11/15

**Comment by eldang** [comment]
Ah, this won't be too bad.  It's just that I decided to move a function between the two JS files and didn't think to warn you.  I'll clear that up in the branch you were working in, and then ping you.

**Pull request merged**
